### Import Libraries

In [3]:
import numpy
import numpy as np
from numpy import pi


In [9]:
# create a one dimensional array
arr1 = np.array([1, 2, 3, 4, 5], dtype='float32')
print(arr1)
print(type(arr1))
print(np.size(arr1))

[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>
5


In [13]:
# create a two dimensional array
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(arr2)
print(type(arr2))
print(np.size(arr2))
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
6
(2, 3)


In [14]:
# vectorized operations
arr3 = np.array([1, 2, 3, 4, 5])    
print(arr3*arr3)

[ 1  4  9 16 25]


### Array from Scratch

In [16]:
# creating a 1D array of zeros
np.zeros(10, dtype=int)
np.zeros((3,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [17]:
# creating a 1D array of ones
np.ones(10, dtype=int)
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
# creating a array of linear sequence
#       start, stop, step  
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
# creating an array of 50 values evenly spaced between 0 and 2
np.linspace(0, 2, 50)

array([0.        , 0.04081633, 0.08163265, 0.12244898, 0.16326531,
       0.20408163, 0.24489796, 0.28571429, 0.32653061, 0.36734694,
       0.40816327, 0.44897959, 0.48979592, 0.53061224, 0.57142857,
       0.6122449 , 0.65306122, 0.69387755, 0.73469388, 0.7755102 ,
       0.81632653, 0.85714286, 0.89795918, 0.93877551, 0.97959184,
       1.02040816, 1.06122449, 1.10204082, 1.14285714, 1.18367347,
       1.2244898 , 1.26530612, 1.30612245, 1.34693878, 1.3877551 ,
       1.42857143, 1.46938776, 1.51020408, 1.55102041, 1.59183673,
       1.63265306, 1.67346939, 1.71428571, 1.75510204, 1.79591837,
       1.83673469, 1.87755102, 1.91836735, 1.95918367, 2.        ])

In [20]:
# creating a 3x3 array of uniformly distributed random values between 0 and 1
np.random.random((3,3))

array([[0.92863442, 0.89402213, 0.15362971],
       [0.1547703 , 0.53515294, 0.08520737],
       [0.34807166, 0.97276246, 0.31802107]])

In [21]:
# create a 3x3 array of normally distributed random values with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.94963904, -1.50224797,  3.44986152],
       [ 0.45489868, -0.35666334, -0.30318297],
       [ 1.91888135,  0.35444336, -0.15446791]])

In [23]:
# create a 3x4 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 4))

array([[3, 5, 8, 9],
       [5, 1, 7, 6],
       [9, 8, 7, 2]])

In [28]:
# creating 1D,2D,3D array using np.randint
np.random.randint(10, size=6) # One-dimensional array
np.random.randint(10, size=(3, 4)) # Two-dimensional array
np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

array([[[2, 6, 0, 2, 3],
        [0, 8, 9, 1, 3],
        [7, 1, 9, 3, 6],
        [9, 9, 3, 2, 2]],

       [[5, 2, 0, 1, 3],
        [9, 8, 8, 3, 9],
        [1, 5, 9, 4, 2],
        [2, 5, 3, 5, 1]],

       [[5, 4, 6, 8, 7],
        [8, 8, 0, 0, 5],
        [6, 8, 6, 1, 9],
        [7, 4, 0, 3, 7]]])

### Array Atributes

In [31]:
arr4 = np.random.randint(10, size=(3, 4, 4))
print("ndim: ", arr4.ndim)
print("shape:", arr4.shape)
print("size: ", arr4.size)
print("dtype:", arr4.dtype)
print("itemsize:", arr4.itemsize, "bytes")
print("nbytes:", arr4.nbytes, "bytes")  # nbytes is the total size of the array

ndim:  3
shape: (3, 4, 4)
size:  48
dtype: int64
itemsize: 8 bytes
nbytes: 384 bytes


### Array Indexing

In [34]:
# accessing array elements
arr5 = np.random.randint(10, size=(3,3))
print(arr5)

[[9 5 8]
 [3 6 7]
 [1 6 6]]


In [37]:
arr5[1, 1] # last element

6

In [38]:
arr5[1][1]

6

In [41]:
arr5[-2,-1]

7

### Array Slicing

In [48]:
arr6 = np.array([8,4,3,4])
arr6[0:2]

array([8, 4])

In [49]:
arr6[::-1]

array([4, 3, 4, 8])

In [51]:
arr6_cpy = arr6[::2].copy()
arr6_cpy

array([8, 3])

In [46]:
arr7 = np.array([[8,4,3,4],
                 [1,2,3,4],
                 [5,6,7,8]])
arr7[0:2, 0:2]

array([[8, 4],
       [1, 2]])

### Reshaping of Array
`reshape()` 

In [55]:
arr8 = np.arange(1, 10).reshape((3, 3))
print(arr8)
arr8.reshape(1,9)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

### Concatenation and Splitting of Arrays

In [58]:
arr9 = np.array([1,2,3])
arr10 = np.array([4,5,6])
np.concatenate([arr9, arr10])

# conacaenate 2D arrays
arr11 = np.array([[1,2,3],[4,5,6]])
np.concatenate([arr11, arr11])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [62]:
# combine 2D arrays along the second axis
np.concatenate([arr11, arr11], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [63]:
# combine arrays of different dimensions
arr12 = np.array([7,8,9])
np.vstack([arr11, arr12])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
arr13 = np.array([[12],[18]])
np.hstack([arr11, arr13])
# arr11

array([[ 1,  2,  3, 12],
       [ 4,  5,  6, 18]])

In [72]:
# splitting arrays
arr14 = np.arange(1, 10)
arr14_1, arr14_2, arr14_3 = np.split(arr14, [3, 7])
print(arr14_1, arr14_2, arr14_3)

[1 2 3] [4 5 6 7] [8 9]


In [81]:
# horizontal split and vertical split
arr15 = np.arange(16).reshape((4, 4))
arr15_1, arr15_2 = np.hsplit(arr15, [2])
arr15_3, arr15_4 = np.vsplit(arr15, [2])
arr15


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [84]:
print("Left part:\n",arr15_1)
print("Right part:\n",arr15_2)

Left part:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Right part:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [85]:
print("Upper part:\n",arr15_3)
print("Lower part:\n",arr15_4)

Upper part:
 [[0 1 2 3]
 [4 5 6 7]]
Lower part:
 [[ 8  9 10 11]
 [12 13 14 15]]
