In [6]:
import numpy as np

arr = np.random.randint(10,size=(5))
arr

array([7, 8, 7, 8, 3])

In [7]:
# arithmatic operations
print(arr + 5)
print(arr - 5)
print(arr * 5)
print(arr / 5)
print(arr // 5)
print(arr % 5)
print(arr ** 2)


[12 13 12 13  8]
[ 2  3  2  3 -2]
[35 40 35 40 15]
[1.4 1.6 1.4 1.6 0.6]
[1 1 1 1 0]
[2 3 2 3 3]
[49 64 49 64  9]


In [8]:
# arithmetical operations using ufuncs
print(np.add(arr,5))
print(np.subtract(arr,5))
print(np.multiply(arr,5))
print(np.divide(arr,5))
print(np.floor_divide(arr,5))
print(np.mod(arr,5))
print(np.power(arr,2))


[12 13 12 13  8]
[ 2  3  2  3 -2]
[35 40 35 40 15]
[1.4 1.6 1.4 1.6 0.6]
[1 1 1 1 0]
[2 3 2 3 3]
[49 64 49 64  9]


In [9]:
# trigonometric functions
print(np.sin(arr))

[0.6569866  0.98935825 0.6569866  0.98935825 0.14112001]


In [10]:
# logarithmic functions and exponential functions
print(np.log(arr))
print(np.exp(arr))


[1.94591015 2.07944154 1.94591015 2.07944154 1.09861229]
[1096.63315843 2980.95798704 1096.63315843 2980.95798704   20.08553692]


In [12]:
arr2 = np.arange(1,5)
print(np.sum(arr2))
np.add.reduce(arr2)

10


10

In [13]:
# accumulation functions
arr3 = np.arange(1,6)
print(np.cumsum(arr3))
print(np.add.accumulate(arr3))

[ 1  3  6 10 15]
[ 1  3  6 10 15]


In [14]:
# summary statistics
arr4 = np.random.randint(10,size=(50))
print("Sum of arr4: ",np.sum(arr4))
print("Mean of arr4: ",np.mean(arr4))
print("Median of arr4: ",np.median(arr4))
print("Standard Deviation of arr4: ",np.std(arr4))
print("Variance of arr4: ",np.var(arr4))
print("Minimum of arr4: ",np.min(arr4))
print("Maximum of arr4: ",np.max(arr4))
print("Percentile of arr4: ",np.percentile(arr4,50))


Sum of arr4:  242
Mean of arr4:  4.84
Median of arr4:  4.5
Standard Deviation of arr4:  2.9145153971114994
Variance of arr4:  8.4944
Minimum of arr4:  0
Maximum of arr4:  9
Percentile of arr4:  4.5


In [18]:
# boolean operations
arr5 = np.random.randint(10,size=(10))
print(arr5)
print(arr5>5)

[2 5 3 5 2 7 1 3 1 2]
[False False False False False  True False False False False]


`any()` `all()`

In [19]:
arr6 = np.arange(0,10)
print(arr6)
print(np.any(arr6>5))
print(np.all(arr6>5))

[0 1 2 3 4 5 6 7 8 9]
True
False


In [29]:
arr7 = np.random.randint(0,10, (3,3))
print(arr7>5)
print(arr7[arr7>5])

[[False  True False]
 [ True  True  True]
 [ True  True False]]
[9 6 6 6 8 9]
